-- Migration: Countries Master Data Enhancement
-- Purpose: Add ISO-3166 compliant columns for DJBC/CEISA integration

-- 1. Add new columns to countries table
ALTER TABLE countries ADD COLUMN IF NOT EXISTS iso_alpha3 VARCHAR(3);
ALTER TABLE countries ADD COLUMN IF NOT EXISTS iso_numeric VARCHAR(3);
ALTER TABLE countries ADD COLUMN IF NOT EXISTS name_en VARCHAR(100);
ALTER TABLE countries ADD COLUMN IF NOT EXISTS name_local VARCHAR(100);
ALTER TABLE countries ADD COLUMN IF NOT EXISTS sub_region VARCHAR(100);
ALTER TABLE countries ADD COLUMN IF NOT EXISTS source VARCHAR(50) DEFAULT 'ISO-3166';
ALTER TABLE countries ADD COLUMN IF NOT EXISTS effective_date DATE DEFAULT CURRENT_DATE;

-- 2. Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_countries_iso_alpha3 ON countries(iso_alpha3);
CREATE INDEX IF NOT EXISTS idx_countries_iso_numeric ON countries(iso_numeric);
CREATE INDEX IF NOT EXISTS idx_countries_region ON countries(region);

-- 3. Insert/Update complete country data (ISO 3166-1)
INSERT INTO countries (code, name, name_en, iso_alpha3, iso_numeric, region, sub_region, is_active, source, effective_date)
VALUES
  ('AF', 'Afghanistan', 'Afghanistan', 'AFG', '004', 'Asia', 'Southern Asia', true, 'ISO-3166', CURRENT_DATE),
  ('AL', 'Albania', 'Albania', 'ALB', '008', 'Europe', 'Southern Europe', true, 'ISO-3166', CURRENT_DATE),
  ('DZ', 'Algeria', 'Algeria', 'DZA', '012', 'Africa', 'Northern Africa', true, 'ISO-3166', CURRENT_DATE),
  ('AS', 'American Samoa', 'American Samoa', 'ASM', '016', 'Oceania', 'Polynesia', true, 'ISO-3166', CURRENT_DATE),
  ('AD', 'Andorra', 'Andorra', 'AND', '020', 'Europe', 'Southern Europe', true, 'ISO-3166', CURRENT_DATE),
  ('AO', 'Angola', 'Angola', 'AGO', '024', 'Africa', 'Middle Africa', true, 'ISO-3166', CURRENT_DATE),
  ('AI', 'Anguilla', 'Anguilla', 'AIA', '660', 'Americas', 'Caribbean', true, 'ISO-3166', CURRENT_DATE),
  ('AQ', 'Antarctica', 'Antarctica', 'ATA', '010', 'Antarctica', 'Antarctica', true, 'ISO-3166', CURRENT_DATE),
  ('AG', 'Antigua and Barbuda', 'Antigua and Barbuda', 'ATG', '028', 'Americas', 'Caribbean', true, 'ISO-3166', CURRENT_DATE),
  ('AR', 'Argentina', 'Argentina', 'ARG', '032', 'Americas', 'South America', true, 'ISO-3166', CURRENT_DATE),
  ('AM', 'Armenia', 'Armenia', 'ARM', '051', 'Asia', 'Western Asia', true, 'ISO-3166', CURRENT_DATE),
  ('AW', 'Aruba', 'Aruba', 'ABW', '533', 'Americas', 'Caribbean', true, 'ISO-3166', CURRENT_DATE),
  ('AU', 'Australia', 'Australia', 'AUS', '036', 'Oceania', 'Australia and New Zealand', true, 'ISO-3166', CURRENT_DATE),
  ('AT', 'Austria', 'Austria', 'AUT', '040', 'Europe', 'Western Europe', true, 'ISO-3166', CURRENT_DATE),
  ('AZ', 'Azerbaijan', 'Azerbaijan', 'AZE', '031', 'Asia', 'Western Asia', true, 'ISO-3166', CURRENT_DATE),
  ('BS', 'Bahamas', 'Bahamas', 'BHS', '044', 'Americas', 'Caribbean', true, 'ISO-3166', CURRENT_DATE),
  ('BH', 'Bahrain', 'Bahrain', 'BHR', '048', 'Asia', 'Western Asia', true, 'ISO-3166', CURRENT_DATE),
  ('BD', 'Bangladesh', 'Bangladesh', 'BGD', '050', 'Asia', 'Southern Asia', true, 'ISO-3166', CURRENT_DATE),
  ('BB', 'Barbados', 'Barbados', 'BRB', '052', 'Americas', 'Caribbean', true, 'ISO-3166', CURRENT_DATE),
  ('BY', 'Belarus', 'Belarus', 'BLR', '112', 'Europe', 'Eastern Europe', true, 'ISO-3166', CURRENT_DATE),
  ('BE', 'Belgium', 'Belgium', 'BEL', '056', 'Europe', 'Western Europe', true, 'ISO-3166', CURRENT_DATE),
  ('BZ', 'Belize', 'Belize', 'BLZ', '084', 'Americas', 'Central America', true, 'ISO-3166', CURRENT_DATE),
  ('BJ', 'Benin', 'Benin', 'BEN', '204', 'Africa', 'Western Africa', true, 'ISO-3166', CURRENT_DATE),
  ('BM', 'Bermuda', 'Bermuda', 'BMU', '060', 'Americas', 'Northern America', true, 'ISO-3166', CURRENT_DATE),
  ('BT', 'Bhutan', 'Bhutan', 'BTN', '064', 'Asia', 'Southern Asia', true, 'ISO-3166', CURRENT_DATE),
  ('BO', 'Bolivia', 'Bolivia', 'BOL', '068', 'Americas', 'South America', true, 'ISO-3166', CURRENT_DATE),
  ('BA', 'Bosnia and Herzegovina', 'Bosnia and Herzegovina', 'BIH', '070', 'Europe', 'Southern Europe', true, 'ISO-3166', CURRENT_DATE),
  ('BW', 'Botswana', 'Botswana', 'BWA', '072', 'Africa', 'Southern Africa', true, 'ISO-3166', CURRENT_DATE),
  ('BR', 'Brazil', 'Brazil', 'BRA', '076', 'Americas', 'South America', true, 'ISO-3166', CURRENT_DATE),
  ('BN', 'Brunei Darussalam', 'Brunei Darussalam', 'BRN', '096', 'Asia', 'South-eastern Asia', true, 'ISO-3166', CURRENT_DATE),
  ('BG', 'Bulgaria', 'Bulgaria', 'BGR', '100', 'Europe', 'Eastern Europe', true, 'ISO-3166', CURRENT_DATE),
  ('BF', 'Burkina Faso', 'Burkina Faso', 'BFA', '854', 'Africa', 'Western Africa', true, 'ISO-3166', CURRENT_DATE),
  ('BI', 'Burundi', 'Burundi', 'BDI', '108', 'Africa', 'Eastern Africa', true, 'ISO-3166', CURRENT_DATE),
  ('CV', 'Cabo Verde', 'Cabo Verde', 'CPV', '132', 'Africa', 'Western Africa', true, 'ISO-3166', CURRENT_DATE),
  ('KH', 'Cambodia', 'Cambodia', 'KHM', '116', 'Asia', 'South-eastern Asia', true, 'ISO-3166', CURRENT_DATE),
  ('CM', 'Cameroon', 'Cameroon', 'CMR', '120', 'Africa', 'Middle Africa', true, 'ISO-3166', CURRENT_DATE),
  ('CA', 'Canada', 'Canada', 'CAN', '124', 'Americas', 'Northern America', true, 'ISO-3166', CURRENT_DATE),
  ('KY', 'Cayman Islands', 'Cayman Islands', 'CYM', '136', 'Americas', 'Caribbean', true, 'ISO-3166', CURRENT_DATE),
  ('CF', 'Central African Republic', 'Central African Republic', 'CAF', '140', 'Africa', 'Middle Africa', true, 'ISO-3166', CURRENT_DATE),
  ('TD', 'Chad', 'Chad', 'TCD', '148', 'Africa', 'Middle Africa', true, 'ISO-3166', CURRENT_DATE),
  ('CL', 'Chile', 'Chile', 'CHL', '152', 'Americas', 'South America', true, 'ISO-3166', CURRENT_DATE),
  ('CN', 'China', 'China', 'CHN', '156', 'Asia', 'Eastern Asia', true, 'ISO-3166', CURRENT_DATE),
  ('CO', 'Colombia', 'Colombia', 'COL', '170', 'Americas', 'South America', true, 'ISO-3166', CURRENT_DATE),
  ('KM', 'Comoros', 'Comoros', 'COM', '174', 'Africa', 'Eastern Africa', true, 'ISO-3166', CURRENT_DATE),
  ('CG', 'Congo', 'Congo', 'COG', '178', 'Africa', 'Middle Africa', true, 'ISO-3166', CURRENT_DATE),
  ('CD', 'Congo (Democratic Republic)', 'Congo (Democratic Republic)', 'COD', '180', 'Africa', 'Middle Africa', true, 'ISO-3166', CURRENT_DATE),
  ('CR', 'Costa Rica', 'Costa Rica', 'CRI', '188', 'Americas', 'Central America', true, 'ISO-3166', CURRENT_DATE),
  ('CI', 'Côte d''Ivoire', 'Côte d''Ivoire', 'CIV', '384', 'Africa', 'Western Africa', true, 'ISO-3166', CURRENT_DATE),
  ('HR', 'Croatia', 'Croatia', 'HRV', '191', 'Europe', 'Southern Europe', true, 'ISO-3166', CURRENT_DATE),
  ('CU', 'Cuba', 'Cuba', 'CUB', '192', 'Americas', 'Caribbean', true, 'ISO-3166', CURRENT_DATE),
  ('CY', 'Cyprus', 'Cyprus', 'CYP', '196', 'Asia', 'Western Asia', true, 'ISO-3166', CURRENT_DATE),
  ('CZ', 'Czechia', 'Czechia', 'CZE', '203', 'Europe', 'Eastern Europe', true, 'ISO-3166', CURRENT_DATE),
  ('DK', 'Denmark', 'Denmark', 'DNK', '208', 'Europe', 'Northern Europe', true, 'ISO-3166', CURRENT_DATE),
  ('DJ', 'Djibouti', 'Djibouti', 'DJI', '262', 'Africa', 'Eastern Africa', true, 'ISO-3166', CURRENT_DATE),
  ('DM', 'Dominica', 'Dominica', 'DMA', '212', 'Americas', 'Caribbean', true, 'ISO-3166', CURRENT_DATE),
  ('DO', 'Dominican Republic', 'Dominican Republic', 'DOM', '214', 'Americas', 'Caribbean', true, 'ISO-3166', CURRENT_DATE),
  ('EC', 'Ecuador', 'Ecuador', 'ECU', '218', 'Americas', 'South America', true, 'ISO-3166', CURRENT_DATE),
  ('EG', 'Egypt', 'Egypt', 'EGY', '818', 'Africa', 'Northern Africa', true, 'ISO-3166', CURRENT_DATE),
  ('SV', 'El Salvador', 'El Salvador', 'SLV', '222', 'Americas', 'Central America', true, 'ISO-3166', CURRENT_DATE),
  ('GQ', 'Equatorial Guinea', 'Equatorial Guinea', 'GNQ', '226', 'Africa', 'Middle Africa', true, 'ISO-3166', CURRENT_DATE),
  ('ER', 'Eritrea', 'Eritrea', 'ERI', '232', 'Africa', 'Eastern Africa', true, 'ISO-3166', CURRENT_DATE),
  ('EE', 'Estonia', 'Estonia', 'EST', '233', 'Europe', 'Northern Europe', true, 'ISO-3166', CURRENT_DATE),
  ('SZ', 'Eswatini', 'Eswatini', 'SWZ', '748', 'Africa', 'Southern Africa', true, 'ISO-3166', CURRENT_DATE),
  ('ET', 'Ethiopia', 'Ethiopia', 'ETH', '231', 'Africa', 'Eastern Africa', true, 'ISO-3166', CURRENT_DATE),
  ('FJ', 'Fiji', 'Fiji', 'FJI', '242', 'Oceania', 'Melanesia', true, 'ISO-3166', CURRENT_DATE),
  ('FI', 'Finland', 'Finland', 'FIN', '246', 'Europe', 'Northern Europe', true, 'ISO-3166', CURRENT_DATE),
  ('FR', 'France', 'France', 'FRA', '250', 'Europe', 'Western Europe', true, 'ISO-3166', CURRENT_DATE),
  ('GA', 'Gabon', 'Gabon', 'GAB', '266', 'Africa', 'Middle Africa', true, 'ISO-3166', CURRENT_DATE),
  ('GM', 'Gambia', 'Gambia', 'GMB', '270', 'Africa', 'Western Africa', true, 'ISO-3166', CURRENT_DATE),
  ('GE', 'Georgia', 'Georgia', 'GEO', '268', 'Asia', 'Western Asia', true, 'ISO-3166', CURRENT_DATE),
  ('DE', 'Germany', 'Germany', 'DEU', '276', 'Europe', 'Western Europe', true, 'ISO-3166', CURRENT_DATE),
  ('GH', 'Ghana', 'Ghana', 'GHA', '288', 'Africa', 'Western Africa', true, 'ISO-3166', CURRENT_DATE),
  ('GR', 'Greece', 'Greece', 'GRC', '300', 'Europe', 'Southern Europe', true, 'ISO-3166', CURRENT_DATE),
  ('GD', 'Grenada', 'Grenada', 'GRD', '308', 'Americas', 'Caribbean', true, 'ISO-3166', CURRENT_DATE),
  ('GT', 'Guatemala', 'Guatemala', 'GTM', '320', 'Americas', 'Central America', true, 'ISO-3166', CURRENT_DATE),
  ('GN', 'Guinea', 'Guinea', 'GIN', '324', 'Africa', 'Western Africa', true, 'ISO-3166', CURRENT_DATE),
  ('GW', 'Guinea-Bissau', 'Guinea-Bissau', 'GNB', '624', 'Africa', 'Western Africa', true, 'ISO-3166', CURRENT_DATE),
  ('GY', 'Guyana', 'Guyana', 'GUY', '328', 'Americas', 'South America', true, 'ISO-3166', CURRENT_DATE),
  ('HT', 'Haiti', 'Haiti', 'HTI', '332', 'Americas', 'Caribbean', true, 'ISO-3166', CURRENT_DATE),
  ('HN', 'Honduras', 'Honduras', 'HND', '340', 'Americas', 'Central America', true, 'ISO-3166', CURRENT_DATE),
  ('HK', 'Hong Kong', 'Hong Kong', 'HKG', '344', 'Asia', 'Eastern Asia', true, 'ISO-3166', CURRENT_DATE),
  ('HU', 'Hungary', 'Hungary', 'HUN', '348', 'Europe', 'Eastern Europe', true, 'ISO-3166', CURRENT_DATE),
  ('IS', 'Iceland', 'Iceland', 'ISL', '352', 'Europe', 'Northern Europe', true, 'ISO-3166', CURRENT_DATE),
  ('IN', 'India', 'India', 'IND', '356', 'Asia', 'Southern Asia', true, 'ISO-3166', CURRENT_DATE),
  ('ID', 'Indonesia', 'Indonesia', 'IDN', '360', 'Asia', 'South-eastern Asia', true, 'ISO-3166', CURRENT_DATE),
  ('IR', 'Iran', 'Iran', 'IRN', '364', 'Asia', 'Southern Asia', true, 'ISO-3166', CURRENT_DATE),
  ('IQ', 'Iraq', 'Iraq', 'IRQ', '368', 'Asia', 'Western Asia', true, 'ISO-3166', CURRENT_DATE),
  ('IE', 'Ireland', 'Ireland', 'IRL', '372', 'Europe', 'Northern Europe', true, 'ISO-3166', CURRENT_DATE),
  ('IL', 'Israel', 'Israel', 'ISR', '376', 'Asia', 'Western Asia', true, 'ISO-3166', CURRENT_DATE),
  ('IT', 'Italy', 'Italy', 'ITA', '380', 'Europe', 'Southern Europe', true, 'ISO-3166', CURRENT_DATE),
  ('JM', 'Jamaica', 'Jamaica', 'JAM', '388', 'Americas', 'Caribbean', true, 'ISO-3166', CURRENT_DATE),
  ('JP', 'Japan', 'Japan', 'JPN', '392', 'Asia', 'Eastern Asia', true, 'ISO-3166', CURRENT_DATE),
  ('JO', 'Jordan', 'Jordan', 'JOR', '400', 'Asia', 'Western Asia', true, 'ISO-3166', CURRENT_DATE),
  ('KZ', 'Kazakhstan', 'Kazakhstan', 'KAZ', '398', 'Asia', 'Central Asia', true, 'ISO-3166', CURRENT_DATE),
  ('KE', 'Kenya', 'Kenya', 'KEN', '404', 'Africa', 'Eastern Africa', true, 'ISO-3166', CURRENT_DATE),
  ('KI', 'Kiribati', 'Kiribati', 'KIR', '296', 'Oceania', 'Micronesia', true, 'ISO-3166', CURRENT_DATE),
  ('KP', 'Korea (North)', 'Korea (North)', 'PRK', '408', 'Asia', 'Eastern Asia', true, 'ISO-3166', CURRENT_DATE),
  ('KR', 'Korea (South)', 'Korea (South)', 'KOR', '410', 'Asia', 'Eastern Asia', true, 'ISO-3166', CURRENT_DATE),
  ('KW', 'Kuwait', 'Kuwait', 'KWT', '414', 'Asia', 'Western Asia', true, 'ISO-3166', CURRENT_DATE),
  ('KG', 'Kyrgyzstan', 'Kyrgyzstan', 'KGZ', '417', 'Asia', 'Central Asia', true, 'ISO-3166', CURRENT_DATE),
  ('LA', 'Laos', 'Laos', 'LAO', '418', 'Asia', 'South-eastern Asia', true, 'ISO-3166', CURRENT_DATE),
  ('LV', 'Latvia', 'Latvia', 'LVA', '428', 'Europe', 'Northern Europe', true, 'ISO-3166', CURRENT_DATE),
  ('LB', 'Lebanon', 'Lebanon', 'LBN', '422', 'Asia', 'Western Asia', true, 'ISO-3166', CURRENT_DATE),
  ('LS', 'Lesotho', 'Lesotho', 'LSO', '426', 'Africa', 'Southern Africa', true, 'ISO-3166', CURRENT_DATE),
  ('LR', 'Liberia', 'Liberia', 'LBR', '430', 'Africa', 'Western Africa', true, 'ISO-3166', CURRENT_DATE),
  ('LY', 'Libya', 'Libya', 'LBY', '434', 'Africa', 'Northern Africa', true, 'ISO-3166', CURRENT_DATE),
  ('LI', 'Liechtenstein', 'Liechtenstein', 'LIE', '438', 'Europe', 'Western Europe', true, 'ISO-3166', CURRENT_DATE),
  ('LT', 'Lithuania', 'Lithuania', 'LTU', '440', 'Europe', 'Northern Europe', true, 'ISO-3166', CURRENT_DATE),
  ('LU', 'Luxembourg', 'Luxembourg', 'LUX', '442', 'Europe', 'Western Europe', true, 'ISO-3166', CURRENT_DATE),
  ('MO', 'Macao', 'Macao', 'MAC', '446', 'Asia', 'Eastern Asia', true, 'ISO-3166', CURRENT_DATE),
  ('MG', 'Madagascar', 'Madagascar', 'MDG', '450', 'Africa', 'Eastern Africa', true, 'ISO-3166', CURRENT_DATE),
  ('MW', 'Malawi', 'Malawi', 'MWI', '454', 'Africa', 'Eastern Africa', true, 'ISO-3166', CURRENT_DATE),
  ('MY', 'Malaysia', 'Malaysia', 'MYS', '458', 'Asia', 'South-eastern Asia', true, 'ISO-3166', CURRENT_DATE),
  ('MV', 'Maldives', 'Maldives', 'MDV', '462', 'Asia', 'Southern Asia', true, 'ISO-3166', CURRENT_DATE),
  ('ML', 'Mali', 'Mali', 'MLI', '466', 'Africa', 'Western Africa', true, 'ISO-3166', CURRENT_DATE),
  ('MT', 'Malta', 'Malta', 'MLT', '470', 'Europe', 'Southern Europe', true, 'ISO-3166', CURRENT_DATE),
  ('MH', 'Marshall Islands', 'Marshall Islands', 'MHL', '584', 'Oceania', 'Micronesia', true, 'ISO-3166', CURRENT_DATE),
  ('MR', 'Mauritania', 'Mauritania', 'MRT', '478', 'Africa', 'Western Africa', true, 'ISO-3166', CURRENT_DATE),
  ('MU', 'Mauritius', 'Mauritius', 'MUS', '480', 'Africa', 'Eastern Africa', true, 'ISO-3166', CURRENT_DATE),
  ('MX', 'Mexico', 'Mexico', 'MEX', '484', 'Americas', 'Central America', true, 'ISO-3166', CURRENT_DATE),
  ('FM', 'Micronesia', 'Micronesia', 'FSM', '583', 'Oceania', 'Micronesia', true, 'ISO-3166', CURRENT_DATE),
  ('MD', 'Moldova', 'Moldova', 'MDA', '498', 'Europe', 'Eastern Europe', true, 'ISO-3166', CURRENT_DATE),
  ('MC', 'Monaco', 'Monaco', 'MCO', '492', 'Europe', 'Western Europe', true, 'ISO-3166', CURRENT_DATE),
  ('MN', 'Mongolia', 'Mongolia', 'MNG', '496', 'Asia', 'Eastern Asia', true, 'ISO-3166', CURRENT_DATE),
  ('ME', 'Montenegro', 'Montenegro', 'MNE', '499', 'Europe', 'Southern Europe', true, 'ISO-3166', CURRENT_DATE),
  ('MA', 'Morocco', 'Morocco', 'MAR', '504', 'Africa', 'Northern Africa', true, 'ISO-3166', CURRENT_DATE),
  ('MZ', 'Mozambique', 'Mozambique', 'MOZ', '508', 'Africa', 'Eastern Africa', true, 'ISO-3166', CURRENT_DATE),
  ('MM', 'Myanmar', 'Myanmar', 'MMR', '104', 'Asia', 'South-eastern Asia', true, 'ISO-3166', CURRENT_DATE),
  ('NA', 'Namibia', 'Namibia', 'NAM', '516', 'Africa', 'Southern Africa', true, 'ISO-3166', CURRENT_DATE),
  ('NR', 'Nauru', 'Nauru', 'NRU', '520', 'Oceania', 'Micronesia', true, 'ISO-3166', CURRENT_DATE),
  ('NP', 'Nepal', 'Nepal', 'NPL', '524', 'Asia', 'Southern Asia', true, 'ISO-3166', CURRENT_DATE),
  ('NL', 'Netherlands', 'Netherlands', 'NLD', '528', 'Europe', 'Western Europe', true, 'ISO-3166', CURRENT_DATE),
  ('NZ', 'New Zealand', 'New Zealand', 'NZL', '554', 'Oceania', 'Australia and New Zealand', true, 'ISO-3166', CURRENT_DATE),
  ('NI', 'Nicaragua', 'Nicaragua', 'NIC', '558', 'Americas', 'Central America', true, 'ISO-3166', CURRENT_DATE),
  ('NE', 'Niger', 'Niger', 'NER', '562', 'Africa', 'Western Africa', true, 'ISO-3166', CURRENT_DATE),
  ('NG', 'Nigeria', 'Nigeria', 'NGA', '566', 'Africa', 'Western Africa', true, 'ISO-3166', CURRENT_DATE),
  ('MK', 'North Macedonia', 'North Macedonia', 'MKD', '807', 'Europe', 'Southern Europe', true, 'ISO-3166', CURRENT_DATE),
  ('NO', 'Norway', 'Norway', 'NOR', '578', 'Europe', 'Northern Europe', true, 'ISO-3166', CURRENT_DATE),
  ('OM', 'Oman', 'Oman', 'OMN', '512', 'Asia', 'Western Asia', true, 'ISO-3166', CURRENT_DATE),
  ('PK', 'Pakistan', 'Pakistan', 'PAK', '586', 'Asia', 'Southern Asia', true, 'ISO-3166', CURRENT_DATE),
  ('PW', 'Palau', 'Palau', 'PLW', '585', 'Oceania', 'Micronesia', true, 'ISO-3166', CURRENT_DATE),
  ('PS', 'Palestine', 'Palestine', 'PSE', '275', 'Asia', 'Western Asia', true, 'ISO-3166', CURRENT_DATE),
  ('PA', 'Panama', 'Panama', 'PAN', '591', 'Americas', 'Central America', true, 'ISO-3166', CURRENT_DATE),
  ('PG', 'Papua New Guinea', 'Papua New Guinea', 'PNG', '598', 'Oceania', 'Melanesia', true, 'ISO-3166', CURRENT_DATE),
  ('PY', 'Paraguay', 'Paraguay', 'PRY', '600', 'Americas', 'South America', true, 'ISO-3166', CURRENT_DATE),
  ('PE', 'Peru', 'Peru', 'PER', '604', 'Americas', 'South America', true, 'ISO-3166', CURRENT_DATE),
  ('PH', 'Philippines', 'Philippines', 'PHL', '608', 'Asia', 'South-eastern Asia', true, 'ISO-3166', CURRENT_DATE),
  ('PL', 'Poland', 'Poland', 'POL', '616', 'Europe', 'Eastern Europe', true, 'ISO-3166', CURRENT_DATE),
  ('PT', 'Portugal', 'Portugal', 'PRT', '620', 'Europe', 'Southern Europe', true, 'ISO-3166', CURRENT_DATE),
  ('PR', 'Puerto Rico', 'Puerto Rico', 'PRI', '630', 'Americas', 'Caribbean', true, 'ISO-3166', CURRENT_DATE),
  ('QA', 'Qatar', 'Qatar', 'QAT', '634', 'Asia', 'Western Asia', true, 'ISO-3166', CURRENT_DATE),
  ('RO', 'Romania', 'Romania', 'ROU', '642', 'Europe', 'Eastern Europe', true, 'ISO-3166', CURRENT_DATE),
  ('RU', 'Russia', 'Russia', 'RUS', '643', 'Europe', 'Eastern Europe', true, 'ISO-3166', CURRENT_DATE),
  ('RW', 'Rwanda', 'Rwanda', 'RWA', '646', 'Africa', 'Eastern Africa', true, 'ISO-3166', CURRENT_DATE),
  ('KN', 'Saint Kitts and Nevis', 'Saint Kitts and Nevis', 'KNA', '659', 'Americas', 'Caribbean', true, 'ISO-3166', CURRENT_DATE),
  ('LC', 'Saint Lucia', 'Saint Lucia', 'LCA', '662', 'Americas', 'Caribbean', true, 'ISO-3166', CURRENT_DATE),
  ('VC', 'Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines', 'VCT', '670', 'Americas', 'Caribbean', true, 'ISO-3166', CURRENT_DATE),
  ('WS', 'Samoa', 'Samoa', 'WSM', '882', 'Oceania', 'Polynesia', true, 'ISO-3166', CURRENT_DATE),
  ('SM', 'San Marino', 'San Marino', 'SMR', '674', 'Europe', 'Southern Europe', true, 'ISO-3166', CURRENT_DATE),
  ('ST', 'Sao Tome and Principe', 'Sao Tome and Principe', 'STP', '678', 'Africa', 'Middle Africa', true, 'ISO-3166', CURRENT_DATE),
  ('SA', 'Saudi Arabia', 'Saudi Arabia', 'SAU', '682', 'Asia', 'Western Asia', true, 'ISO-3166', CURRENT_DATE),
  ('SN', 'Senegal', 'Senegal', 'SEN', '686', 'Africa', 'Western Africa', true, 'ISO-3166', CURRENT_DATE),
  ('RS', 'Serbia', 'Serbia', 'SRB', '688', 'Europe', 'Southern Europe', true, 'ISO-3166', CURRENT_DATE),
  ('SC', 'Seychelles', 'Seychelles', 'SYC', '690', 'Africa', 'Eastern Africa', true, 'ISO-3166', CURRENT_DATE),
  ('SL', 'Sierra Leone', 'Sierra Leone', 'SLE', '694', 'Africa', 'Western Africa', true, 'ISO-3166', CURRENT_DATE),
  ('SG', 'Singapore', 'Singapore', 'SGP', '702', 'Asia', 'South-eastern Asia', true, 'ISO-3166', CURRENT_DATE),
  ('SK', 'Slovakia', 'Slovakia', 'SVK', '703', 'Europe', 'Eastern Europe', true, 'ISO-3166', CURRENT_DATE),
  ('SI', 'Slovenia', 'Slovenia', 'SVN', '705', 'Europe', 'Southern Europe', true, 'ISO-3166', CURRENT_DATE),
  ('SB', 'Solomon Islands', 'Solomon Islands', 'SLB', '090', 'Oceania', 'Melanesia', true, 'ISO-3166', CURRENT_DATE),
  ('SO', 'Somalia', 'Somalia', 'SOM', '706', 'Africa', 'Eastern Africa', true, 'ISO-3166', CURRENT_DATE),
  ('ZA', 'South Africa', 'South Africa', 'ZAF', '710', 'Africa', 'Southern Africa', true, 'ISO-3166', CURRENT_DATE),
  ('SS', 'South Sudan', 'South Sudan', 'SSD', '728', 'Africa', 'Eastern Africa', true, 'ISO-3166', CURRENT_DATE),
  ('ES', 'Spain', 'Spain', 'ESP', '724', 'Europe', 'Southern Europe', true, 'ISO-3166', CURRENT_DATE),
  ('LK', 'Sri Lanka', 'Sri Lanka', 'LKA', '144', 'Asia', 'Southern Asia', true, 'ISO-3166', CURRENT_DATE),
  ('SD', 'Sudan', 'Sudan', 'SDN', '729', 'Africa', 'Northern Africa', true, 'ISO-3166', CURRENT_DATE),
  ('SR', 'Suriname', 'Suriname', 'SUR', '740', 'Americas', 'South America', true, 'ISO-3166', CURRENT_DATE),
  ('SE', 'Sweden', 'Sweden', 'SWE', '752', 'Europe', 'Northern Europe', true, 'ISO-3166', CURRENT_DATE),
  ('CH', 'Switzerland', 'Switzerland', 'CHE', '756', 'Europe', 'Western Europe', true, 'ISO-3166', CURRENT_DATE),
  ('SY', 'Syria', 'Syria', 'SYR', '760', 'Asia', 'Western Asia', true, 'ISO-3166', CURRENT_DATE),
  ('TW', 'Taiwan', 'Taiwan', 'TWN', '158', 'Asia', 'Eastern Asia', true, 'ISO-3166', CURRENT_DATE),
  ('TJ', 'Tajikistan', 'Tajikistan', 'TJK', '762', 'Asia', 'Central Asia', true, 'ISO-3166', CURRENT_DATE),
  ('TZ', 'Tanzania', 'Tanzania', 'TZA', '834', 'Africa', 'Eastern Africa', true, 'ISO-3166', CURRENT_DATE),
  ('TH', 'Thailand', 'Thailand', 'THA', '764', 'Asia', 'South-eastern Asia', true, 'ISO-3166', CURRENT_DATE),
  ('TL', 'Timor-Leste', 'Timor-Leste', 'TLS', '626', 'Asia', 'South-eastern Asia', true, 'ISO-3166', CURRENT_DATE),
  ('TG', 'Togo', 'Togo', 'TGO', '768', 'Africa', 'Western Africa', true, 'ISO-3166', CURRENT_DATE),
  ('TO', 'Tonga', 'Tonga', 'TON', '776', 'Oceania', 'Polynesia', true, 'ISO-3166', CURRENT_DATE),
  ('TT', 'Trinidad and Tobago', 'Trinidad and Tobago', 'TTO', '780', 'Americas', 'Caribbean', true, 'ISO-3166', CURRENT_DATE),
  ('TN', 'Tunisia', 'Tunisia', 'TUN', '788', 'Africa', 'Northern Africa', true, 'ISO-3166', CURRENT_DATE),
  ('TR', 'Turkey', 'Turkey', 'TUR', '792', 'Asia', 'Western Asia', true, 'ISO-3166', CURRENT_DATE),
  ('TM', 'Turkmenistan', 'Turkmenistan', 'TKM', '795', 'Asia', 'Central Asia', true, 'ISO-3166', CURRENT_DATE),
  ('TV', 'Tuvalu', 'Tuvalu', 'TUV', '798', 'Oceania', 'Polynesia', true, 'ISO-3166', CURRENT_DATE),
  ('UG', 'Uganda', 'Uganda', 'UGA', '800', 'Africa', 'Eastern Africa', true, 'ISO-3166', CURRENT_DATE),
  ('UA', 'Ukraine', 'Ukraine', 'UKR', '804', 'Europe', 'Eastern Europe', true, 'ISO-3166', CURRENT_DATE),
  ('AE', 'United Arab Emirates', 'United Arab Emirates', 'ARE', '784', 'Asia', 'Western Asia', true, 'ISO-3166', CURRENT_DATE),
  ('GB', 'United Kingdom', 'United Kingdom', 'GBR', '826', 'Europe', 'Northern Europe', true, 'ISO-3166', CURRENT_DATE),
  ('US', 'United States', 'United States', 'USA', '840', 'Americas', 'Northern America', true, 'ISO-3166', CURRENT_DATE),
  ('UY', 'Uruguay', 'Uruguay', 'URY', '858', 'Americas', 'South America', true, 'ISO-3166', CURRENT_DATE),
  ('UZ', 'Uzbekistan', 'Uzbekistan', 'UZB', '860', 'Asia', 'Central Asia', true, 'ISO-3166', CURRENT_DATE),
  ('VU', 'Vanuatu', 'Vanuatu', 'VUT', '548', 'Oceania', 'Melanesia', true, 'ISO-3166', CURRENT_DATE),
  ('VA', 'Vatican City', 'Vatican City', 'VAT', '336', 'Europe', 'Southern Europe', true, 'ISO-3166', CURRENT_DATE),
  ('VE', 'Venezuela', 'Venezuela', 'VEN', '862', 'Americas', 'South America', true, 'ISO-3166', CURRENT_DATE),
  ('VN', 'Vietnam', 'Vietnam', 'VNM', '704', 'Asia', 'South-eastern Asia', true, 'ISO-3166', CURRENT_DATE),
  ('YE', 'Yemen', 'Yemen', 'YEM', '887', 'Asia', 'Western Asia', true, 'ISO-3166', CURRENT_DATE),
  ('ZM', 'Zambia', 'Zambia', 'ZMB', '894', 'Africa', 'Eastern Africa', true, 'ISO-3166', CURRENT_DATE),
  ('ZW', 'Zimbabwe', 'Zimbabwe', 'ZWE', '716', 'Africa', 'Eastern Africa', true, 'ISO-3166', CURRENT_DATE)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  name_en = EXCLUDED.name_en,
  iso_alpha3 = EXCLUDED.iso_alpha3,
  iso_numeric = EXCLUDED.iso_numeric,
  region = EXCLUDED.region,
  sub_region = EXCLUDED.sub_region,
  source = EXCLUDED.source,
  effective_date = EXCLUDED.effective_date,
  updated_at = NOW();

-- 4. Create function to get country code for XML mapping
CREATE OR REPLACE FUNCTION get_country_iso_alpha2(country_id UUID)
RETURNS VARCHAR(2) AS $$
BEGIN
  RETURN (SELECT code FROM countries WHERE id = country_id);
END;
$$ LANGUAGE plpgsql STABLE;
