ALTER TABLE pib_documents ADD COLUMN IF NOT EXISTS source VARCHAR(20) DEFAULT 'MANUAL';
ALTER TABLE pib_documents ADD COLUMN IF NOT EXISTS synced_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE peb_documents ADD COLUMN IF NOT EXISTS source VARCHAR(20) DEFAULT 'MANUAL';
ALTER TABLE peb_documents ADD COLUMN IF NOT EXISTS synced_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE ceisa_manifests ADD COLUMN IF NOT EXISTS source VARCHAR(20) DEFAULT 'MANUAL';

ALTER TABLE ceisa_pkbsi ADD COLUMN IF NOT EXISTS source VARCHAR(20) DEFAULT 'MANUAL';

ALTER TABLE ceisa_kendaraan ADD COLUMN IF NOT EXISTS source VARCHAR(20) DEFAULT 'MANUAL';
